### ISSUE TITLE
请教一个在线代码中设计器问题

### ISSUE THREAD

**Issue by aa310958153** [wengwh/plumdo-work#13]
在线设计器是不是少了很多东西啊。比如事件配置

**Comment by aa310958153** [comment]
项目部署 都ok了 然后发现设计器少了很多东东

**Comment by wengwh** [comment]
@aa310958153 定义的文件：stencilset.json，我删掉了一些组件，因为定位是非代码开发使用，所以很多组件目前还无非直接给人配置用所以先屏蔽了。
